# Dependencies
markdown:         redcarpet
highlighter:      pygments

name: Name
title: Title
description: Description
meta_description: "meta description"
layouts: ./_layouts
subtitle: subtitle

excerpt_separator:  '<!-- more -->'

paginate: 5

baseurl: /